<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1" import="com.cs336.pkg.*"%>
<!--Import some libraries that have classes that we need -->
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<link rel="stylesheet" type="text/css" href="css/style.css"/> <!--  now we will be able to use CSS in our code -->
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">

<style>
body {
  	background-image: url("CloudImage.jpeg");
  	background-repeat: no-repeat;
  	background-size: cover;
  	text-align: center;
  	background-position: fixed;
  	background-top:0;
  	background-left:0;
  	background-min-width: 100%;
  	background-min-height: 100%;
}

h1 {
	color: #0074D9;
  	font-family: geometric sans-serif;
  	font-size: 200%;
  	text-align: center;
}

p{
	font-size: 200%;
}
input{
	background-color: transparent;
	font-family: geometric sans-serif;
	font-size: 75%;
}

</style>

<title>Administrator: Sales Report Selection</title>
</head>
<body>

<%
ApplicationDB db = new ApplicationDB();

Connection con = db.getConnection();
String select;
PreparedStatement ps;
ResultSet result;

%>

<h1>What would you like a sales report of?</h1>

<h2>Get a summary listing of revenue generated by a flight</h2>
<form method = "post" action = "AdminSalesReportView.jsp">
Flight Number:
<select name = "flightNumber">

<%
	ps = con.prepareStatement("SELECT flight_number FROM OnlineResTravelSystem.Flight ORDER BY flight_number ASC");
	
	result = ps.executeQuery();
	
	while(result.next()) {
		int flightNumber = result.getInt("flight_number");
		out.print("<option value = \"" + result.getString("flight_number") +  "\">" + flightNumber + "</option>");
	}
	
	result.close();
	ps.close();
%>

</select>

<input type = "submit" value = "Go">
</form>


<h2>Get a summary listing of revenue generated by an airline (revenue from all the flights of that airline)</h2>
<form method = "post" action = "AdminSalesReportView.jsp">
Airline Company: 
<select name = "airlineCompany">
<%
select = "SELECT CompName,2_letter_ID FROM OnlineResTravelSystem.Airline_Company";
ps = con.prepareStatement(select);
result = ps.executeQuery();


while(result.next()) {
	String compName = result.getString("compName");
	String id = result.getString("2_letter_ID");
	out.print("<option value = \"" + id + "\">" + id + " - " + compName + "</option>"); 
}
result.close();
ps.close();
%>
</select>
<input type = "submit" value = "Go">
</form>

<h2>Get a summary listing of revenue generated by a customer</h2>
<form action = "AdminSalesReportView.jsp">
Customer: 
<select name = "userID">
<%
select = "SELECT * FROM OnlineResTravelSystem.User WHERE User_Type = \"1\"";
ps = con.prepareStatement(select);
result = ps.executeQuery();
while(result.next()) {
	out.print("<option value = \"" + result.getString("User_ID") + "\">" + result.getString("First_Name") + " " + result.getString("Last_Name") + " (Username: " + result.getString("Username") + ")" + "</option>");
}
result.close();
ps.close();
%>
</select>
<input type = "submit" value = "Go">
</form>

<h2>Get a sales report for a particular month</h2>
<form action = "AdminSalesReportView.jsp">
Month (yyyy-mm): 
<input type = "text" name = "date" value = "2019-12">
<input type = "submit" value = "Go">
</form>
<br>

<%
con.close();
%>

<form method = "post" action = "AdminDashboard.jsp">
<input type = "submit" value = "Go back to administrator dashboard">
</form>
</body>
</html>